import { Manufacturer } from './rest/models/manufacturer.model';
import { Cheese } from './rest/models/cheese.model';
import { Review } from './rest/models/review.model';

export const manufacturers: Manufacturer[] = [
  {
    id: '1',
    name: 'Cheese Co.',
    country: 'USA',
    foundedYear: 1954,
    website: 'www.cheeseco.com',
    employeeCount: 500,
    isOrganic: true,
    headquarters: {
      city: 'Wisconsin',
      address: '123 Cheese Street',
      postalCode: '53703',
      country: 'USA',
    },
    certificates: [
      {
        name: 'FDA Approval',
        issueDate: '2022-01-15',
        expiryDate: '2025-01-14',
        issuingBody: 'FDA',
        certificationNumber: 'FDA-2022-001',
      },
      {
        name: 'Organic Certification',
        issueDate: '2023-03-20',
        expiryDate: '2024-03-19',
        issuingBody: 'USDA',
        certificationNumber: 'ORG-2023-123',
      },
    ],
    producedCheeses: ['1', '6'],
  },
  {
    id: '2',
    name: 'Dairy Best',
    country: 'Canada',
    foundedYear: 1982,
    website: 'www.dairybest.ca',
    employeeCount: 250,
    isOrganic: false,
    headquarters: {
      city: 'Ontario',
      address: '456 Dairy Lane',
      postalCode: 'K1A 0B1',
      country: 'Canada',
    },
    certificates: [
      {
        name: 'CFIA Certification',
        issueDate: '2021-05-10',
        expiryDate: '2024-05-09',
        issuingBody: 'CFIA',
        certificationNumber: 'CFIA-2021-456',
      },
      {
        name: 'ISO 9001',
        issueDate: '2022-08-15',
        expiryDate: '2025-08-14',
        issuingBody: 'ISO',
        certificationNumber: 'ISO-2022-789',
      },
    ],
    producedCheeses: ['2'],
  },
  {
    id: '3',
    name: 'Alpine Delights',
    country: 'Switzerland',
    foundedYear: 1899,
    website: 'www.alpinedelights.ch',
    employeeCount: 150,
    isOrganic: true,
    headquarters: {
      city: 'Bern',
      address: '789 Alpine Road',
      postalCode: '3000',
      country: 'Switzerland',
    },
    certificates: [
      {
        name: 'Swiss Quality',
        issueDate: '2020-11-20',
        expiryDate: '2023-11-19',
        issuingBody: 'Swiss Quality Association',
        certificationNumber: 'SQA-2020-321',
      },
      {
        name: 'Bio-Suisse',
        issueDate: '2021-02-25',
        expiryDate: '2024-02-24',
        issuingBody: 'Bio-Suisse',
        certificationNumber: 'BIO-2021-654',
      },
    ],
    producedCheeses: ['3', '4', '5'],
  },
];

export const cheeses: Cheese[] = [
  {
    id: '1',
    name: 'Cheddar',
    type: 'Hard',
    ageInMonths: 12,
    price: 15.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '45%',
      protein: '25g',
      calories: 402,
      sodium: '621mg',
    },
    origin: 'Wisconsin',
    isArtisanal: false,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Vacuum-sealed',
      material: 'Plastic',
      recyclable: true,
      weight: 250,
    },
    reviews: [{ id: '1' }, { id: '2' }],
  },
  {
    id: '2',
    name: 'Brie',
    type: 'Soft',
    ageInMonths: 2,
    price: 12.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '60%',
      protein: '20g',
      calories: 334,
      sodium: '629mg',
    },
    origin: 'Ontario',
    isArtisanal: true,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Wooden box',
      material: 'Wood',
      recyclable: false,
      weight: 200,
    },
    reviews: [{ id: '3' }],
  },
  {
    id: '3',
    name: 'Emmental',
    type: 'Hard',
    ageInMonths: 4,
    price: 22.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '45%',
      protein: '28g',
      calories: 393,
      sodium: '600mg',
    },
    origin: 'Switzerland',
    isArtisanal: true,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Wax-coated',
      material: 'Wax',
      recyclable: false,
      weight: 300,
    },
    reviews: [],
  },
  {
    id: '4',
    name: 'Gruyère',
    type: 'Hard',
    ageInMonths: 6,
    price: 24.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '49%',
      protein: '30g',
      calories: 413,
      sodium: '560mg',
    },
    origin: 'Switzerland',
    isArtisanal: true,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Vacuum-sealed',
      material: 'Plastic',
      recyclable: true,
      weight: 250,
    },
    reviews: [{ id: '4' }, { id: '7' }],
  },
  {
    id: '5',
    name: 'Raclette',
    type: 'Semi-hard',
    ageInMonths: 3,
    price: 19.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '45%',
      protein: '21g',
      calories: 357,
      sodium: '590mg',
    },
    origin: 'Switzerland',
    isArtisanal: true,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Vacuum-sealed',
      material: 'Plastic',
      recyclable: true,
      weight: 400,
    },
    reviews: [{ id: '5' }],
  },
  {
    id: '6',
    name: 'Aged Cheddar',
    type: 'Hard',
    ageInMonths: 24,
    price: 18.99,
    milkType: 'Cow',
    nutritionalInfo: {
      fatContent: '51%',
      protein: '24g',
      calories: 428,
      sodium: '640mg',
    },
    origin: 'Wisconsin',
    isArtisanal: true,
    allergens: [
      {
        name: 'Milk',
        severity: 'high',
        description: 'Contains dairy proteins',
      },
    ],
    packaging: {
      type: 'Wax-coated',
      material: 'Wax',
      recyclable: false,
      weight: 200,
    },
    reviews: [{ id: '6' }],
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    cheeseId: '1',
    reviewer: {
      id: 'USR001',
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@email.com',
      purchaseHistory: 12,
    },
    ratings: {
      flavor: 5,
      texture: 4,
      value: 5,
      packaging: 4,
      overall: 5,
    },
    comment: 'Great cheese!',
    verifiedPurchase: true,
    datePosted: '2023-01-15',
    helpfulVotes: 45,
    wouldRecommend: true,
  },
  {
    id: '2',
    cheeseId: '1',
    reviewer: {
      id: 'USR002',
      firstName: 'Mary',
      lastName: 'Johnson',
      email: 'mary.johnson@email.com',
      purchaseHistory: 8,
    },
    ratings: {
      flavor: 3,
      texture: 4,
      value: 2,
      packaging: 3,
      overall: 3,
    },
    comment: 'Not bad',
    verifiedPurchase: true,
    datePosted: '2023-02-20',
    helpfulVotes: 12,
    wouldRecommend: false,
  },
  {
    id: '3',
    cheeseId: '2',
    reviewer: {
      id: 'USR003',
      firstName: 'Pierre',
      lastName: 'Dubois',
      email: 'pierre.dubois@email.com',
      purchaseHistory: 15,
    },
    ratings: {
      flavor: 4,
      texture: 5,
      value: 4,
      packaging: 4,
      overall: 4,
    },
    comment: 'Very creamy',
    verifiedPurchase: true,
    datePosted: '2023-03-10',
    helpfulVotes: 28,
    wouldRecommend: true,
  },
  {
    id: '4',
    cheeseId: '4',
    reviewer: {
      id: 'USR004',
      firstName: 'Hans',
      lastName: 'Mueller',
      email: 'hans.mueller@email.com',
      purchaseHistory: 20,
    },
    ratings: {
      flavor: 5,
      texture: 5,
      value: 4,
      packaging: 5,
      overall: 5,
    },
    comment: 'Perfect for fondue, amazing quality!',
    verifiedPurchase: true,
    datePosted: '2023-04-15',
    helpfulVotes: 52,
    wouldRecommend: true,
  },
  {
    id: '5',
    cheeseId: '5',
    reviewer: {
      id: 'USR005',
      firstName: 'Sophie',
      lastName: 'Laurent',
      email: 'sophie.laurent@email.com',
      purchaseHistory: 7,
    },
    ratings: {
      flavor: 5,
      texture: 4,
      value: 4,
      packaging: 5,
      overall: 4,
    },
    comment: 'Excellent for raclette dinner parties!',
    verifiedPurchase: true,
    datePosted: '2023-05-02',
    helpfulVotes: 34,
    wouldRecommend: true,
  },
  {
    id: '6',
    cheeseId: '6',
    reviewer: {
      id: 'USR006',
      firstName: 'David',
      lastName: 'Wilson',
      email: 'david.wilson@email.com',
      purchaseHistory: 15,
    },
    ratings: {
      flavor: 5,
      texture: 5,
      value: 3,
      packaging: 4,
      overall: 4,
    },
    comment: 'Sharp and complex flavor, but a bit pricey',
    verifiedPurchase: true,
    datePosted: '2023-05-20',
    helpfulVotes: 41,
    wouldRecommend: true,
  },
  {
    id: '7',
    cheeseId: '4',
    reviewer: {
      id: 'USR007',
      firstName: 'Marie',
      lastName: 'Dubois',
      email: 'marie.dubois@email.com',
      purchaseHistory: 9,
    },
    ratings: {
      flavor: 4,
      texture: 5,
      value: 3,
      packaging: 5,
      overall: 4,
    },
    comment: 'Classic Swiss cheese, great quality',
    verifiedPurchase: true,
    datePosted: '2023-06-01',
    helpfulVotes: 27,
    wouldRecommend: true,
  },
];
